language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
dist: trusty
sudo: false
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - npm install
script:
  - npm test
